language: java
jdk:
- oraclejdk9
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: bintray
  file: target/descriptor.json
  user: fbacchella
  skip_cleanup: true
  on: release
  key:
    secure: TlGWdjQpHQKgwjVdVpHEt/5IkdOZxD9l7rz+bnUcD+4rCiwb+0m9KxxBYKwIhhOz+saju9Hg2yD2Sy9Y6gccPOT/9lZBF1qNB3o4146HeRQ83VtZVKM20duFT6NYb33RzmUVZxI8MZDfhDDzWavLeQ/HggfcT4pD9nvg/y4xyNS6RFIgQuwotmwV+6pLHHqf2MQ+pabQXcH5kRbliEX0Bm/xfq3DZClaU9hiOPvzvwV/xpKbR4OGCTjzrYCcDwt46bhGyzHy7hIfIInJEGLxkPSEFg5ZmJBUqOZuHdPPbzybBTh1lcl01J+l3bqCRAEz6RH96LMT4alx6RKFTE6kZHUauODaVr07x8SbcBD7hDPKu9XmI7KHoGVQKtVrPzWlyyhY3hbIxoYQTixd8nZ6s9LFUjWQuZpYcMAgtTgOlRrrvuR4kYVtortUWVTDPCp4btYZoHqSYzTJBvW2i5qK+00wvjARdpUwxP/lcqhgN9g24biiFij/HFgT7qTz4gG5+njCi97z7SsANaXb69Q7atAwdkaequgQH+UQW59BrQx/dBOJHVQWdd4TKSY4usqWjYkW3XAmi+hzuNyibTatnD8KtdFmzNX3yPxPYrZt1UHsbE5tFx65flJoP7K3LazVKWfrD2EAZC7pcLELiiwXPNG2C3LHqvJLmFtkFqfKhgY=
notifications:
  irc:
  - irc.freenode.org#jrds
