language: java
jdk:
  - openjdk8
  - openjdk9
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: bintray
  file: target/descriptor.json
  user: fbacchella
  skip_cleanup: true
  on: release
  key:
    secure: TlGWdjQpHQKgwjVdVpHEt/5IkdOZxD9l7rz+bnUcD+4rCiwb+0m9KxxBYKwIhhOz+saju9Hg2yD2Sy9Y6gccPOT/9lZBF1qNB3o4146HeRQ83VtZVKM20duFT6NYb33RzmUVZxI8MZDfhDDzWavLeQ/HggfcT4pD9nvg/y4xyNS6RFIgQuwotmwV+6pLHHqf2MQ+pabQXcH5kRbliEX0Bm/xfq3DZClaU9hiOPvzvwV/xpKbR4OGCTjzrYCcDwt46bhGyzHy7hIfIInJEGLxkPSEFg5ZmJBUqOZuHdPPbzybBTh1lcl01J+l3bqCRAEz6RH96LMT4alx6RKFTE6kZHUauODaVr07x8SbcBD7hDPKu9XmI7KHoGVQKtVrPzWlyyhY3hbIxoYQTixd8nZ6s9LFUjWQuZpYcMAgtTgOlRrrvuR4kYVtortUWVTDPCp4btYZoHqSYzTJBvW2i5qK+00wvjARdpUwxP/lcqhgN9g24biiFij/HFgT7qTz4gG5+njCi97z7SsANaXb69Q7atAwdkaequgQH+UQW59BrQx/dBOJHVQWdd4TKSY4usqWjYkW3XAmi+hzuNyibTatnD8KtdFmzNX3yPxPYrZt1UHsbE5tFx65flJoP7K3LazVKWfrD2EAZC7pcLELiiwXPNG2C3LHqvJLmFtkFqfKhgY=
notifications:
  irc:
  - irc.freenode.org#jrds
addons:
  sonarcloud:
    organization: fbacchella-github
    token:
      secure: "Gr5od7EBRfrHYP0q+0BVHUWxxl2dKzK5F5UeIH8h+eAqE8aroEPzzHraoHSgAh59Ie4ljvHPQPCjUqJpaO/LxIxjZkWBGVWAJQeIZMGhcUHc/1Je3otTwYbqKcNPP3ZuRf31q7SX83yygdUqDczT8tRTH63lmpTK9Ae6ffDHbA/NZF+/1u5lGGirw2kYY2g5aZ5yxRVURTcODCvXvpUy/aPA5w3r0Bk7fbvTQfedFUZPj1MVjCGt8WJo8Mgv6h1bfsl2vWnfpzlu8gyaYADHgVqO7ogS8EQwt/P8SJnH6qxUrHTEf46BWs49p1gCh+2HZukqNgJYcoYaYAhIjogv7BYr6Oli9p7qppQAAUNlxyrAaj4XCn5iCMEs+BBGdYBMd71ub5CyIat0kdOnLU7x6VUAykUXoze5goDmYKYeGKTT9YlSZ+Rju8LDaJfEdRqZz01zbNbUjAtTjBEn3DONRbujHWa9pOdQLTuV0z8jExMrn7zDiv9xNBlC1FeX+uQRTQ5AC9u/5mGp8o7WgGczj42xj97dApCNgypMllXwQPHmqGRJ/PEodjVAoq4X/i7CNtXf3LZUYIjPCYGNv91qHxBRbs+BOKNPSGE1m6T7lDNI5F9T4G7KAEUax5+jLr7nOdmftRylOkfsWXD5AqZKyi5pxdOB8hPWDUClTGX04mY="
matrix:
  include:
    - jdk: openjdk10
      script:
        - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
      on:
          branch: master
script:
  - mvn clean package deploy
